AWSTemplateFormatVersion: "2010-09-09"
Description: This stack create a CFN macro for map array operations.
Parameters:
  EnvironmentName:
    Type: String
  AppName:
    Type: String
Resources:
  MapStringArrayFuncRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        -
          PolicyName: !Sub '${EnvironmentName}-${AppName}-lambda-manage-logs'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
  MapStringArrayFunc:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Code:
        ZipFile: !Rain::Embed lambda_function.py
      Role: !GetAtt MapStringArrayFuncRole.Arn
      FunctionName: !Sub "${EnvironmentName}-${AppName}-cfn-macro-map-string-array"
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          APP_NAME: !Ref AppName
  LGCMapStringArrayFunc:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MapStringArrayFunc}
      RetentionInDays: 5
  MacroMapStringArrayFunc:
    Type: AWS::CloudFormation::Macro
    Properties:
      Description: A macro for map array operations
      FunctionName: !GetAtt MapStringArrayFunc.Arn
      Name: 'map-string-array-macro'
