AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
  AppName:
    Type: String
  EcommerBucketAccess:
    Type: String
Resources:
  EcommerceIamUser:
    Type: AWS::IAM::User
    Properties:
      Tags: 
        - Key: projectName
          Value: !Ref AppName
        - Key: environment
          Value: !Ref EnvironmentName
      UserName: !Sub '${EnvironmentName}-${AppName}-platform-application-user'
  
  EcommerceIamAccessKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: 'Active'
      UserName: !Ref EcommerceIamUser
  EcommerceIamUserCredentialsSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${EnvironmentName}-${AppName}-app-user-credentials"
      Description: This secret store the credentials of the IAM user for this app.
      SecretString: !Sub
        - '{"AccessKeyId":"${UserName}", "SecretAccessKey":"${Password}"}'
        - UserName: !Ref EcommerceIamAccessKeys
          Password: !GetAtt EcommerceIamAccessKeys.SecretAccessKey
  
  EcommerceIamPrincipalPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${EnvironmentName}-${AppName}-platform-resources-access
      Users:
        - !Ref EcommerceIamAccessKeys
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Ref EcommerBucketAccess
              - !Sub '${EcommerBucketAccess}/*'
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref EcommerceIamUserCredentialsSecret

Outputs:
  EcommerceIamUserName:
    Value: !Ref EcommerceIamUser
    Description: Name of the IAM user
  EcommerceIamUserCredentialsSecretArn:
    Value: !Ref EcommerceIamUserCredentialsSecret
    Description: Arn whre stored access credentials